### ISSUE TITLE
Blank Plugins page

### ISSUE THREAD

**Issue by Visiluna** [rsanchez/json#46]
I have been running JSON 1.0.2 on EE 2.6.1 with no issues. In preparing to upgrade EE to 2.9.3, I first installed JSON 1.1.6. After installing this, the control panel Plugins page is now blank. I rolled back to 1.0.2 and the Plugins page loads fine. I also had an older copy of JSON 1.1.2 that I installed, and the Plugins page still loads. I'm having the problem only with 1.1.6.

EE 2.6.1
PHP 5.3.19 (JSON support enabled)
MySQL 5.0.8

Any thoughts?

**Comment by rsanchez** [comment]
Can you go to the releases page and try 1.1.5? https://github.com/rsanchez/json/tags

If that doesn't work try 1.1.4 and so forth until you find the last working version. This would really help me debug. Thanks.

**Comment by Visiluna** [comment]
The Plugins page loaded fine with 1.1.5.

**Comment by rsanchez** [comment]
The devot-ee version was incorrect. I've updated so that the Devotee version downloads the correct 1.1.6 now. Thanks.
